meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: 18f_cf_leader_z1
    templates:
    - name: 18f-cf
      release: 18f-cf
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: 18f_cf_z1
    templates:
    - name: 18f-cf
      release: 18f-cf
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      18f_cf:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
